name: ESLint
on: 
  workflow_call
jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  sudo npm install -g eslint@8.57.0
            - name: Updating .eslintrc.yaml
              run: |
                wget -O .eslintrc.yaml https://raw.githubusercontent.com/odoo-ps/psmx-ci-cd/master/.eslintrc.yaml
            - name: Run ESLint
              run: eslint $(git ls-files '*.js')
